version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    govet:
      disable:
        - fieldalignment
        - lostcancel
        - shadow
      enable-all: true
    nolintlint:
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - client/examples_test.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - client/examples_test.go
      - third_party$
      - builtin$
      - examples$
