linters:
  disable-all: true
  enable:
    # All code is ready for:
    - errcheck
    - gofumpt
    - goimports
    - govet
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    # ToDo:
    #- gocritic
    #- golint
linters-settings:
  nolintlint:
    allow-unused: false
    require-specific: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - lostcancel
      - shadow
issues:
  exclude-files:
    - client/examples_test.go
